version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_container
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./db.scripts:/scripts
    command: /bin/bash -c "/scripts/setup.sh & /opt/mssql/bin/sqlservr"
    networks:
      - example-network

  wiremock-example:
    container_name: wiremock-example
    image: rodolpheche/wiremock
    ports:
      - "9001:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: --verbose
    networks:
      - example-network

  redis:
    image: redis:latest
    container_name: redis-example
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - example-network

volumes:
  redis-data:

networks:
  example-network: